<link rel="stylesheet" type="text/css" href="<?php echo base_url(); ?>assets/shared/css/jquery-ui.css"/>
<script type="text/javascript"  src="<?php echo base_url(); ?>assets/shared/js/jquery-ui.min.js"></script>
<script language="javascript">
$(document).ready(function() {
$frmAddUser = $('#frmAddUser').serialize();
user_role_change($("#user_role").val());
$( "#from,#to" ).datepicker({
changeMonth: true,
changeYear: true,
dateFormat:"yy-mm-dd",
minDate:0
})
});
function user_role_change(role)
{
if(role==2)
{
$("#optional_number input").val("");
$("#optional_number").hide();
$("#container_psychologist").hide();
$("#container_difficulty").hide();
$("#container_group").hide();
$("#container_notify").show();
$("#container_permission").show();
$("#container_difficulties").show();
$("#container_difficulty_role").show();
$("#container_sms_notify").hide();
$("#activate_app_li").hide();
$(".web_version").hide();
$("#patient_access_li").hide();
$("#patient_create_li").hide();
$("#communication").hide();
$("#container_group_psy").show();
}
else
{
$("#optional_number").show();
$("#container_psychologist").show();
$("#container_difficulty").show();
$("#container_group").show();
$("#container_notify").hide();
$("#container_permission").hide();
$("#container_difficulties").hide();
$("#container_difficulty_role").hide();
$("#container_sms_notify").show();
$("#activate_app_li").show();
$(".web_version").show();
$("#patient_access_li").show();
$("#patient_create_li").show();
$("#communication").show();
$("#container_group_psy").hide();
}
$('.table tbody tr:even').addClass('even');
$('.table tbody tr:odd').addClass('odd');
$('.table tbody tr:last-child').addClass('last');
$('.table tbody tr th:first-child, tr td:first-child').addClass('first');
$('.table tbody tr th:last-child, tr td:last-child').addClass('last');
}
</script>
<style type="text/css">
.even{
background: #f5f5f5;
}
.odd{
background: #e6e6e6;
}
</style>
<?php
//dd($rows);
$usertype = getUserType();
$permission = $rows->permission;
$permission = json_decode($permission,true);
$edit_psy_per = $psy->permission;
$edit_psy_per = json_decode($edit_psy_per,true);
//dd($edit_psy_per);
$rows->first_name = $this->encryption->decrypt($rows->first_name);
$rows->last_name = $this->encryption->decrypt($rows->last_name);
$rows->email = $this->encryption->decrypt($rows->email);
$rows->contact_number = $this->encryption->decrypt($rows->contact_number);
$rows->contact_number_1 = $this->encryption->decrypt($rows->contact_number_1);

$sess_permission = $this->setting_model->getPermissionOfPsy();
$sess_permission=json_decode($sess_permission,true);
//dd($sess_permission);
$psychologistid = $this->session->userdata('user_id');
?>
<div id="box1" class="box box-100">
<!-- box full-width -->
<div class="boxin padt20">
<!-- <div class="header"> -->
<h3><?php echo $this->lang->line("add_new_user"); ?><?= lang('add_user') ?></h3>
<!-- </div> -->
<form name="frmAddUser" id="frmAddUser" method="post">
<ul class="addstage">
<li style=" margin-top:15px;">
<label class="label"><strong><?= lang('username') ?></strong></label>
<input type="hidden"  id="checkEmail" value="<?php if ($task == "edit_user")
echo "1"; ?>" />
<input onblur="checkUsername(this.value)" type="text" name="username" id="username" class="inputs" maxlength="200" value="<?php echo $rows->username; ?>" />
<span id="error_email"></span>
<input name="oldUsername" type="hidden" id="oldUsername" value="<?php echo set_value('oldUsername',$rows->username )?>" />
</li>
<li>
<label class="label"><strong><?= lang('password') ?></strong></label>
<input type="hidden" name="reset_password" id="reset_password" value="0">
<input type="password" name="autogeneratedpw" id="autogeneratedpw" class="password inputs" maxlength="200" />
<button type="button" id="eye" style="display:none;">
<img src="<?php echo base_url().'images/icons/' ?>eye-16.png" alt="eye" />
</button>
<a href="#" onclick="autoGeneratepw()" ><?= lang('generate_password') ?></a>
</li>
<li>
<label class="label"><strong><?= lang('first_name') ?></strong></label>
<input type="text" name="firstName" id="firstName" class="inputs" maxlength="200" value="<?php echo set_value('firstName',$rows->first_name); ?>" />
</li>
<li>
<label class="label"><strong><?= lang('last_name') ?></strong></label>
<input type="text" name="lastName" id="lastName" class="inputs" maxlength="200" value="<?php echo set_value('lastName',$rows->last_name); ?>" />
</li>
<li>
<label class="label"><strong><?= lang('email') ?></strong></label>
<input type="text" name="email" id="email" class="inputs" maxlength="200" value="<?php echo set_value('email',$rows->email); ?>" onchange="validateEmail(this)" />
<label style="display:none;color:red;font-size:13px;" id="error_email_user"><em><?= lang('js_invalid_email') ?></em></label>
</li>
<li>
<label class="label"><strong><?= lang('address') ?></strong></label>
<input type="text" name="address" id="address" class="inputs" maxlength="200" value="<?php echo set_value('address',$rows->address); ?>" />
</li>
<li>
<label class="label"><strong><?= lang('city') ?></strong></label>
<input type="text" name="city" id="city" class="inputs" maxlength="200" value="<?php echo set_value('city',$rows->city); ?>" />
</li>
<li>
<label class="label"><strong>User Role</strong></label>
<select name="user_role" id="user_role" onchange="user_role_change(this.value);">
<?php
if (!isset($rows->user_role) || $rows->user_role == 1) {
$selected = 'selected="selected"';
}
if ($rows->user_role == 2) {
$selected1 = 'selected="selected"';
}
?>
<?php
foreach ($sess_permission['rights_per_group'] as $key => $grp_data) {
if($grp_data['manage_users']== 1){
$create = true;
break;
}else{
$create = false;
}
}
if ($create || $rows->psychologist_id == $psychologistid || $rows->id==$psychologistid) { ?>
<option <?php echo $selected; ?>  value="1">User</option>
<?php }
foreach ($sess_permission['rights_per_group'] as $key => $grp_data) {
if($grp_data['create_psychologists']== 1 || $grp_data['manage_psychologists']== 1 ){
$create = true;
break;
}else{
$create = false;
}
}
if ($create || $rows->psychologist_id == $psychologistid || $rows->id==$psychologistid) { ?>
<option <?php echo $selected1; ?>  value="2" >Psychologist</option>
<?php } ?>
</select>
</li>
<li id="communication">
<label class="label"><strong>Psychologist Communication</strong></label>
<label class="label"><input type="radio" id="communication" name="communication" value="1" <?php echo ($rows->communication == "1") ? 'checked="checked"' : ''; ?>/>Off</label> &nbsp;&nbsp;&nbsp;<label class="label">
<input type="radio" id="communication" name="communication" value="0" <?php echo ($rows->communication != "1") ? 'checked="checked"' : ''; ?>/> On</label>
</li>
<li>
<label class="label"><strong><?= lang('contact_number') ?></strong></label>
<input type="text" name="contact_number" id="contact_number" class="inputs" maxlength="200" value="<?php echo set_value('contact_number',$rows->contact_number); ?>" />
<label style="display:none;color:red;font-size:13px;" id="error_contact_number"><em><?= lang('invalid_contact_number') ?></em></label>
<br/><label style="margin-left:210px;font-size:12px">(<?= lang('number_format') ?>: 070-000000)</label>
</li>
<li id="optional_number">
<label class="label"><strong>Optional Contact Number</strong></label>
<input type="text" name="contact_number_1" id="contact_number_1" class="inputs" maxlength="200" value="<?php echo set_value('contact_number_1',$rows->contact_number_1); ?>" />
<label style="display:none;color:red;" id="error_contact_number_1"><em>Invalid Contact Number</em></label>
<br/><label style="margin-left:210px;font-size:12px">(<?= lang('number_format') ?>: 070-000000)</label>
</li>
<li id="container_sms_notify">
<label class="label"><strong><?= lang('sms_email_notification') ?></strong></label>
<label class="label"><input type="radio" id="sms_notify" name="sms_notify" value="1" <?php echo ($rows->sms_notify == "1") ? 'checked="checked"' : ''; ?>/> <?= lang('yes') ?></label> &nbsp;&nbsp;&nbsp;<label class="label">
<input type="radio" id="sms_notify" name="sms_notify" value="0" <?php echo ($rows->sms_notify != "1") ? 'checked="checked"' : ''; ?>/> <?= lang('no') ?></label>
</li>
<li id="container_group">
<label class="label"><strong><?= lang('group') ?></strong></label>
<?php
$psy_grp=[];
$grpidarr=[];
foreach ($sess_permission['rights_per_group'] as $key => $diff_data) {
$grpidarr[]=$key;
}
foreach ($sess_permission['rights_per_group'] as $key => $diff_data) {
if($diff_data['manage_users'] == 1){
$checkmanage[]=$key;
}
}
$checkmanage = implode(',', $checkmanage);
$grpid=implode(',', $grpidarr);
$psychologist_grp = $this->db->query('select * from bip_group where id IN ('.$grpid.')');
$psy_grp=$psychologist_grp->result();
foreach ($sess_permission['rights_per_group'] as $key => $grp_data) {
if($grp_data['manage_users']== "1"){
$create = true;
break;
}else{
$create = false;
}
}
?>
<select name="group" id="group" onchange="getSelectedGrpId('<?php echo $checkmanage ?>')">
<option><?php echo lang('choose_group'); ?></option>
<?php
if ($create) {
foreach($group as $data){?>
<option
<?php
if ($rows->group_id == $data->id) {
echo 'selected="selected"';
}
?> value="<?php echo $data->id; ?>"><?php echo $data->group_name; ?></option>
<?php
}
} else{
foreach ($psy_grp as $data) {
?>
<option  <?php
if ($rows->group_id == $data->id) {
echo 'selected="selected"';
}
?> value="<?php echo $data->id; ?>"><?php echo $data->group_name; ?></option>
<?php
}
} ?>
</select>
</li>
<li id="container_psychologist">
<label class="label"><strong><?= lang('psychologist') ?></strong></label>
<select name="psychologist" id="psychologist">
<option><?php echo lang('choose_psychologist'); ?></option>
</select>
</li>
<li id="container_difficulty">
<label class="label"><strong><?= lang('diagnosis') ?> </strong></label>
<?php
$psy_diff=[];
//dd($sess_permission);
foreach ($sess_permission['rights_per_difficulty'] as $key => $diff_data) {
$diff_id=$key;
$psychologist_diff = $this->db->query('select * from bip_difficulty where id = '.$diff_id);
$psy_diff[]=$psychologist_diff->row();
}
$result_diff = $this->stage_model->getAllDifficultyByLang();
$select = $rows->difficulty_id;
$options = '<select name="difficulty" id="difficulty">';
$option_found = false;
if(!empty($result_diff))
foreach ($result_diff as $rows_diff) {
if ($select == $rows_diff->id)
{
$do_select = 'selected="selected"';
$option_found = true;
}
else
$do_select = "";
$options .= '<option ' . $do_select . ' value=' . $rows_diff->id . '>' . $rows_diff->difficulty . '</option>';
}
$options .= '</select>';
if(empty($select) || $option_found)
echo $options;
else
{
$query = $this->db->query('select difficulty from bip_difficulty where id = '.$select);
$difficulty_name        = $query->row()->difficulty;
echo '<select name="difficulty" id="difficulty"><option selected="selected" value="'.$select.'">'.$difficulty_name.'</option></select>';
}
?>
</li>
<li id="container_notify">
<label class="label"><strong><?= lang('email_notification') ?></strong></label>
<input type="radio" id="email_notify" name="email_notify" value="1" <?php echo ($rows->email_notify == "1") ? 'checked="checked"' : ''; ?>/> <?= lang('yes') ?> &nbsp;&nbsp;&nbsp;
<input type="radio" id="email_notify" name="email_notify" value="0" <?php echo ($rows->email_notify != "1") ? 'checked="checked"' : ''; ?>/> <?= lang('no') ?>
</li>
<li id="container_group_psy" class="hasAccordion">
<?php $permission = json_decode($rows->permission,true);
$created_by = $rows->created_by;
//$psychologistID = $this->session->userdata('user_id');
$sess_permission =$this->setting_model->getPermissionOfPsy();
$sess_permission=json_decode($sess_permission,true);
//$edit_psy_id = $this->input->post('userId');
//echo $edit_psy_id;die();
//echo '<pre>';print_r($permission);
?>
<input type="checkbox" name="container_group_psy_controller" id="container_group_psy_controller" />
<label class="label asAccordion" for="container_group_psy_controller"><strong>Groups &amp; Permissions</strong></label>
<div class="accordionTable">
<table class="table fullwidth fleft">
<thead>
<tr>
<td><strong>Group name</strong></td>
<td align="center">Treat patients</td>
<td align="center">Manage Users</td>
<td align="center">Create psychologists</td>
<td align="center">Manage Psychologists</td>
<td align="center">Extract data</td>
</tr>
</thead>
<tbody>
<?php
if($edit_psy_id == $psychologistid && $edit_psy_per){
foreach ($edit_psy_per['rights_per_group'] as $key1 => $diff_data) {
$edit_psy_grp_id[]=$key1;
}
//dd($edit_psy_grp_id);
foreach ($edit_psy_grp_id as $grp_id) {
$psychologist_grp = $this->db->query('select * from bip_group where id = '.$grp_id);
$psy_grp_itself[]=$psychologist_grp->row();
}
//echo '<pre>';print_r($psy_grp_itself);exit;
$i = 0;
foreach ($psy_grp_itself as $data) {
?>
<tr>
<td><?php echo $data->group_name; ?></td>
<input name="new_group_id[]" type="hidden"  value='<?= $data->id ?>'>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['treat_patients']; ?>
<?php if($edit_psy_per['rights_per_group'][$data->id]['treat_patients'] == 0 ){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['treat_patients'] == "1" && $disabled == 'disabled'){
?>
<input name="treat_patients_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="treat_patients_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='treat_patients_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['treat_patients'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['manage_users']; ?>
<?php if($edit_psy_per['rights_per_group'][$data->id]['manage_users'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['manage_users'] == "1" && $disabled == 'disabled' ){
?>
<input name="manage_users_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="manage_users_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='manage_users_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['manage_users'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['create_psychologists']; ?>
<?php if($edit_psy_per['rights_per_group'][$data->id]['create_psychologists'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['create_psychologists'] == "1" && $disabled == 'disabled' ){
?>
<input name="create_psychologists_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="create_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='create_psychologists_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['create_psychologists'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['manage_psychologists']; ?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php if($edit_psy_per['rights_per_group'][$data->id]['manage_psychologists'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['manage_psychologists'] == "1" && $disabled == 'disabled' ){
?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='manage_psychologists_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['manage_psychologists'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['extract_data']; ?>
<?php if($edit_psy_per['rights_per_group'][$data->id]['extract_data'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['extract_data'] == "1" && $disabled == 'disabled' ){
?>
<input name="extract_data_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="extract_data_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='extract_data_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['extract_data'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
</tr>
<?php $i++; }
}else{
if($edit_psy_per){
//dd($sess_permission);
$i = 0;
$psy_grp=[];
foreach ($edit_psy_per['rights_per_group'] as $key1 => $diff_data) {
$edit_psy_grp_id[]=$key1;
}
//dd($edit_psy_grp_id);
foreach ($sess_permission['rights_per_group'] as $key => $value) {
$psy_grp_id[] = $key;
}
if($edit_psy_grp_id){
$combine_grp = array_merge($edit_psy_grp_id,$psy_grp_id);
$combine_grp = array_unique($combine_grp);
}else{
$combine_grp = $psy_grp_id;
}
//dd($combine_grp);
foreach ($combine_grp as $grp_id) {
$psychologist_grp = $this->db->query('select * from bip_group where id = '.$grp_id);
$psy_grp[]=$psychologist_grp->row();
}
$i = 0;
//echo '<pre>';print_r($psy_grp);exit;
foreach ($psy_grp as $data) {
	//print_r($data);exit;
	//print_r($sess_permission['rights_per_group'][$data->id]);
?>
<tr>
<td><?php echo $data->group_name; ?></td>
<input name="new_group_id[]" type="hidden"  value='<?= $data->id ?>'>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['treat_patients']; ?>
<?php if($sess_permission['rights_per_group'][$data->id]['create_psychologists'] == 1 || $sess_permission['rights_per_group'][$data->id]['manage_users'] == 1 || ($sess_permission['rights_per_group'][$data->id]['treat_patients'] == 1 && $sess_permission['rights_per_group'][$data->id]['manage_psychologists'] == 1) /*|| $created_by == $psychologistid*/){
$disabled = '';
}else{
$disabled = 'disabled';
}
if($edit_psy_per['rights_per_group'][$data->id]['treat_patients'] == "1" && $disabled == 'disabled'){
?>
<input name="treat_patients_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="treat_patients_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='treat_patients_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['treat_patients'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['manage_users']; ?>
<?php if($sess_permission['rights_per_group'][$data->id]['manage_users'] == 0 /*&& $created_by != $psychologistid*/){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['manage_users'] == "1" && $disabled == 'disabled' ){
?>
<input name="manage_users_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="manage_users_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='manage_users_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['manage_users'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['create_psychologists']; ?>
<?php if($sess_permission['rights_per_group'][$data->id]['create_psychologists'] == 0  /*&& $created_by != $psychologistid*/){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['create_psychologists'] == "1" && $disabled == 'disabled' ){
?>
<input name="create_psychologists_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="create_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='create_psychologists_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['create_psychologists'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['manage_psychologists']; ?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php if($sess_permission['rights_per_group'][$data->id]['manage_psychologists'] == 0  /*&& $created_by != $psychologistid*/){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['manage_psychologists'] == "1" && $disabled == 'disabled' ){
?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='manage_psychologists_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['manage_psychologists'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $edit_psy_per['rights_per_group'][$data->id]['extract_data']; ?>
<?php if($sess_permission['rights_per_group'][$data->id]['manage_psychologists'] == 0 /*&& $created_by != $psychologistid*/){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_group'][$data->id]['extract_data'] == "1" && $disabled == 'disabled' ){
?>
<input name="extract_data_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="extract_data_<?= $i ?>" type="hidden"  value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='extract_data_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_group'][$data->id]['extract_data'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
</tr>
<?php $i++; }
}else{
$i = 0;
$psy_grp=[];
foreach ($sess_permission['rights_per_group'] as $key => $diff_data) {
$grp_id=$key;
//echo $grp_id;
//echo '&nbsp';
$psychologist_grp = $this->db->query('select * from bip_group where id = '.$grp_id);
$psy_grp[]=$psychologist_grp->row();
}
$i = 0;
//echo '<pre>';print_r($psy_grp);exit;
foreach ($psy_grp as $data) {
?>
<tr>
<td><?php echo $data->group_name; ?></td>
<input name="new_group_id[]" type="hidden"  value='<?= $data->id ?>'>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['treat_patients']; ?>
<input name="treat_patients_<?= $i ?>" type="hidden"  value='0'>
<?php if($sess_permission['rights_per_group'][$data->id]['create_psychologists'] == 1 || $sess_permission['rights_per_group'][$data->id]['manage_users'] == 1 || ($sess_permission['rights_per_group'][$data->id]['treat_patients'] == 1 && $sess_permission['rights_per_group'][$data->id]['manage_psychologists'] == 1) || $created_by == $psychologistid){
$disabled = '';
}else{
$disabled = 'disabled';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='treat_patients_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['manage_users']; ?>
<input name="manage_users_<?= $i ?>" type="hidden"  value='0'>
<?php if($permission['rights_per_group'][$data->id]['manage_users'] == 0 && $created_by != $psychologistid){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='manage_users_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['create_psychologists']; ?>
<input name="create_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php if($permission['rights_per_group'][$data->id]['create_psychologists'] == 0  && $created_by != $psychologistid){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='create_psychologists_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['manage_psychologists']; ?>
<input name="manage_psychologists_<?= $i ?>" type="hidden"  value='0'>
<?php if($permission['rights_per_group'][$data->id]['manage_psychologists'] == 0  && $created_by != $psychologistid){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='manage_psychologists_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $groupCheckedState = $sess_permission['rights_per_group'][$data->id]['extract_data']; ?>
<input name="extract_data_<?= $i ?>" type="hidden"  value='0'>
<?php if($permission['rights_per_group'][$data->id]['manage_psychologists'] == 0 && $created_by != $psychologistid){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='extract_data_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
</tr>
<?php $i++; }
} }
?>
</tbody>
</table>
</div>
</li>
<li id="container_difficulties" class="hasAccordion">
<?php
$sess_permission =$this->setting_model->getPermissionOfPsy();
$sess_permission=json_decode($sess_permission,true);
$created_by = $rows->created_by;
$permission = json_decode($rows->permission,true);
//print_r($permission);
?>
<input type="checkbox" name="container_difficulty_psy_controller" id="container_difficulty_psy_controller" />
<label class="label asAccordion" for="container_difficulty_psy_controller"><strong>Difficulties &amp; Permissions</strong></label>
<div class="accordionTable">
<table class="table fullwidth fleft">
<thead>
<tr>
<td><strong>Difficulty name</strong></td>
<td align="center">Edit Difficulty</td>
<td align="center">Give rights to edit difficulty</td>
</tr>
</thead>
<tbody>
<?php
if($edit_psy_per){
$psy_diff=[];
foreach ($edit_psy_per['rights_per_difficulty'] as $key1 => $diff_data) {
$edit_psy_diff_id[]=$key1;
}
foreach ($sess_permission['rights_per_difficulty'] as $key => $diff_data) {
$psy_diff_id[]=$key;
}
if($edit_psy_diff_id){
$combine_diff = array_merge($edit_psy_diff_id,$psy_diff_id);
$combine_diff = array_unique($combine_diff);
}else{
$combine_diff = $psy_diff_id;
}
foreach ($combine_diff as $diff_id) {
$psychologist_diff = $this->db->query('select * from bip_difficulty where id = '.$diff_id);
$psy_diff[]=$psychologist_diff->row();
}
$i = 0;
foreach ($psy_diff as $data) {
//print_r($data);exit();
?>
<tr>
<td><?php echo $data->difficulty; ?></td>
<?php $difficultyCheckedState = $edit_psy_per['rights_per_difficulty'][$data->id]['edit_difficulty']; ?>
<input name="new_difficulty_id[]" type="hidden"  value='<?= $data->id ?>'>
<td align="center">
<label class="customCheckbox">
<?php if(($sess_permission['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty'] == 0) && $edit_psy_id != $psychologistid){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_difficulty'][$data->id]['edit_difficulty'] == "1" && $disabled =='disabled'){ ?>
<input name="edit_difficulty_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="edit_difficulty_<?= $i ?>" type="hidden"  value='0'>
<?php }
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='edit_difficulty_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_difficulty'][$data->id]['edit_difficulty'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $difficultyCheckedState = $edit_psy_per['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty']; ?>
<?php if($sess_permission['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty'] == 0 ){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty'] == "1" && $disabled =='disabled'){ ?>
<input name="give_rights_to_edit_difficulty_<?= $i ?>" type="hidden"  value='1'>
<?php }else{ ?>
<input name="give_rights_to_edit_difficulty_<?= $i ?>" type="hidden"  value='0'>
<?php }
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name ='give_rights_to_edit_difficulty_<?= $i ?>' value='1' <?php echo ($edit_psy_per['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty'] == "1") ? 'checked="checked"' : ''; ?>>
<span></span>
</label>
</td>
</tr>
<?php $i++; }
}else{
$psy_diff=[];
foreach ($sess_permission['rights_per_difficulty'] as $key => $diff_data) {
$diff_id=$key;
$psychologist_diff = $this->db->query('select * from bip_difficulty where id = '.$diff_id);
$psy_diff[]=$psychologist_diff->row();
}
$i = 0;
foreach ($psy_diff as $data) {
//print_r($data);exit();
?>
<tr>
<td><?php echo $data->difficulty; ?></td>
<?php $difficultyCheckedState = $sess_permission['rights_per_difficulty'][$data->id]['edit_difficulty']; ?>
<input name="new_difficulty_id[]" type="hidden"  value='<?= $data->id ?>'>
<input name="edit_difficulty_<?= $i ?>" type="hidden"  value='0'>
<td align="center">
<label class="customCheckbox">
<?php if($permission['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name='edit_difficulty_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
<td align="center">
<label class="customCheckbox">
<?php $difficultyCheckedState = $sess_permission['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty']; ?>
<input name="give_rights_to_edit_difficulty_<?= $i ?>" type="hidden"  value='0'>
<?php if($permission['rights_per_difficulty'][$data->id]['give_rights_to_edit_difficulty'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name ='give_rights_to_edit_difficulty_<?= $i ?>' value='1'>
<span></span>
</label>
</td>
</tr>
<?php $i++; } }?>
</tbody>
</table>
</div>
</li>
<li id="container_permission">
<label class="label" style="margin-top:20px"><strong> Other Permission</strong></label>
<table style="border : 1px solid green; width:502px;">
<tbody style="float:left;padding:10px">
<tr>
<td>
<label class="customCheckbox">
<?php if($edit_psy_per){ ?>
<?php
$otherRightsCheckedState = $edit_psy_per['other_rights']['create_new_difficulty']; ?>
<?php if($sess_permission['other_rights']['create_new_difficulty'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['other_rights']['create_new_difficulty'] == "1" && $disabled == 'disabled'){ ?>
<input type='hidden' name='create_new_difficulty' value='1'>
<?php }else{ ?>
<input type='hidden' name='create_new_difficulty' value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name ='create_new_difficulty' id="createNewDifficulty" value='1' <?php echo ($edit_psy_per['other_rights']['create_new_difficulty'] == "1") ? 'checked="checked"' : ''; ?>>
<?php }else{ ?>
<?php
$otherRightsCheckedState = $sess_permission['other_rights']['create_new_difficulty']; ?>
<input type='hidden' name='create_new_difficulty' value='0'>
<?php if($permission['other_rights']['create_new_difficulty'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>"id="createNewDifficulty" name ='create_new_difficulty' value='1'>
<?php } ?>
<span></span>
</label>
</td>
<td style="padding-left:5px"><label for="createNewDifficulty" class="cursorPointer">Create New Difficulty</label></td>
</tr>
<tr>
<td>
<label class="customCheckbox">
<?php if($edit_psy_per){ ?>
<?php $otherRightsCheckedState = $edit_psy_per['other_rights']['create_new_group']; ?>
<input type='hidden' name='create_new_group' value='0'>
<?php if($sess_permission['other_rights']['create_new_group'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
if($edit_psy_per['other_rights']['create_new_group'] == "1" && $disabled == 'disabled'){ ?>
<input type='hidden' name='create_new_group' value='1'>
<?php }else{ ?>
<input type='hidden' name='create_new_group' value='0'>
<?php } ?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name ='create_new_group' id="createNewGroup" value='1' <?php echo ($edit_psy_per['other_rights']['create_new_group'] == "1") ? 'checked="checked"' : ''; ?>>
<?php }else{ ?>
<?php $otherRightsCheckedState = $sess_permission['other_rights']['create_new_group']; ?>
<input type='hidden' name='create_new_group' value='0'>
<?php if($permission['other_rights']['create_new_group'] == 0){
$disabled = 'disabled';
}else{
$disabled = '';
}
?>
<input <?=$disabled; ?> type='checkbox' class="checkbox_checked <?=$disabled; ?>" name ='create_new_group' id="createNewGroup" value='1'>
<?php } ?>
<span></span>
</label>
</td>
<td style="padding-left:5px"><label class="cursorPointer" for="createNewGroup">Create New Group</label></td>
</tr>
</tbody>
</table>
</li>
<li>
<label class="label"><strong><?= lang('active_from') ?></strong></label>
<input type="text" id="from"  class="inputs"  name="from" value="<?php echo $rows->active_from; ?>"/>
<span style=" padding: 0 5px;"><?= lang('active_to') ?></span>
<input type="text" id="to" name="to" class="inputs" value="<?php echo $rows->active_to; ?>" />
</li>
<li id="activate_app_li">
<label class="label"><strong><?= lang('activate_app') ?></strong></label>
<label class="label"><input type="radio" id="app_status" name="app_status" value="1" <?php echo ($rows->app_status == "1") ? 'checked="checked"' : ''; ?>/> <?= lang('yes') ?></label> &nbsp;&nbsp;&nbsp;<label class="label">
<input type="radio" id="app_status" name="app_status" value="0" <?php echo ($rows->app_status != "1") ? 'checked="checked"' : ''; ?>/> <?= lang('no') ?></label>
</li>
<li id="activate_app_li" class="web_version">
<label class="label"><strong>Use web version of App</strong></label>
<input type="radio" id="app_web_version" name="app_web_version" value="1" <?php echo ($rows->app_web_version == "1") ? 'checked="checked"' : ''; ?>/> Yes &nbsp;&nbsp;&nbsp;
<input type="radio" id="app_web_version" name="app_web_version" value="0" <?php echo ($rows->app_web_version != "1") ? 'checked="checked"' : ''; ?>/> No
</li>
<li id="patient_access_li">
<label for="patient_access"><strong><?= lang('let_patient_change_reminder') ?></strong></label>
<input type="hidden" name="patient_access" value="0">
<input type="checkbox" id="patient_access" name="patient_access" <?php echo ($rows->patient_access == "1") ? 'checked="checked"' : ''; ?> value="1">
</li>
<?php
if ($rows->id) {
$patient_access_create_checked = ($rows->patient_access_create == "1") ? 'checked="checked"' : '';
}else{
$patient_access_create_checked = 'checked="checked"';
}
?>
<li id="patient_create_li">
<label for="patient_access_create"><strong><?= lang('let_patient_change_task') ?></strong></label>
<input type="hidden" name="patient_access_create" value="0">
<input type="checkbox" id="patient_access_create" name="patient_access_create" <?php echo $patient_access_create_checked; ?> value="1">
</li>
<li>
<label class="label"><strong><?= lang('status') ?></strong></label>
<select name="status" id="status">
<option <?php if ($rows->status == "1" || !isset($rows->status))
echo "selected"; ?> value="1"><?= lang('active') ?></option>
<option  <?php if ($rows->status != "1" && isset($rows->status))
echo "selected"; ?> value="0"><?= lang('inactive') ?></option>
</select>
</li>
<li style="clear:left;  margin-top:15px;">
<input type="button" name="btnSave" id="btnSave" value="<?= lang('save') ?>"  onclick="addUser();" class="button" />
<input type="button" name="btnCancel" id="btnCancel" value="<?= lang('cancel') ?>" onclick="listUser('id asc','');" class="button" />
</li>
<input type="hidden" name="userId" id="hidid" value="<?php echo $rows->id; ?>" />
</ul>
</form>
</div>
</div>
<?php echo validation_errors('<p class="error">'); ?>
<script type="text/javascript">
function getGrpIdByDrpDwn(){
$('#group').val();
}
function show() {
var p = document.getElementById('autogeneratedpw');
p.setAttribute('type', 'text');
}
function hide() {
var p = document.getElementById('autogeneratedpw');
p.setAttribute('type', 'password');
}
var pwShown = 0;
document.getElementById("eye").addEventListener("click", function () {
if (pwShown == 0) {
pwShown = 1;
show();
} else {
pwShown = 0;
hide();
}
}, false);
function autoGeneratepw()
{
if($usertype =='admin')
{
$path=$sitePath+"/user/admin/createPassword";
}
else
{
$path=$sitePath+"/user/createPassword";;
}
$.ajax({
type:"post",
url:$path,
asyn:true,
data:{},
success: function(response)
{
$("#autogeneratedpw").val('').val(response).show();
$("#eye").show();
$("#autogeneratedpw").val(response);
$("#eye").show();
$("#reset_password").val(1);
// $("#autogeneratedpw").valid();
}
});
}
$(function(){
getSelectedGrpId("",'<?php echo $rows->psychologist_id ?>',false);
//console.log(psyid);
if($("#hidid").val()){
$("#autogeneratedpw").hide();
}
$('.checkbox_checked' ).on('change' ,  function() {
//debugger;
if($("#hidid").val() == $currentUserId){
var $this = $(this);
var checked = $this.prop("checked");
if(!checked)
{
var confirmation = confirm  ('Removed permission cannot be restored by yourself. Do you still want to continue?');
if(confirmation)
{
$this.prop("checked", false);
}else{
$this.prop("checked", true);
}
}
}
});
})
</script>
